# Druid数据源
spring:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://127.0.0.1:3306/canteen?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC&useJDBCCompliantTimezoneShift=true
      username: root
      password: 12345678
      enable: true
      max-active: 20
      initial-size: 5
      max-wait: 5000
      min-idle: 5
      validation-query: select 1
      filter: stat,wall,slf4j
      # 监控配置
      stat-view-servlet:
        enabled: true
        login-username: admin
        login-password: admin
        allow:
        deny:
        url-pattern:
          - "/druid/*"

  # 前台和后台的日期格式转化
  jackson:  # 后台-->前台
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  # mvc @DateFormat注解在属性上
  mvc:
    date-format: yyyy-MM-dd HH:mm:ss
  # 模板引擎设置
  thymeleaf:
    cache: false
    enabled: true
  # 文件上传
  servlet:
    multipart:
      max-file-size: 5MB

# mybatis-plus
mybatis-plus:
  mapper-locations:
    - classpath:mapper/*/*Mapper.xml
  global-config:
    db-config:
      id-type: auto
    banner: true
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
# shiro
shiro:
  hash-algorithm-name: md5  # 加密的算法
  hash-iterations: 2  # 散列的次数
  anon-urls:  # 放行的地址
    - /index.html*
    - /sys/toLogin*
    - /login/login*
    - /resources/**
    - /login/getCode*
  login-url: /index.html  # 登录的地址
  log-out-url: /login/logout* # 注销的地址
  authc-ulrs:
    - /**




